### ISSUE TITLE
Can't change filter during recording

### ISSUE THREAD

**Issue by stonyz** [MasayukiSuda/CameraRecorder-android#12]
Reproduce steps,
1. Start recording
2. change filter
3. check the video file, find the 1st filter is applied for the whole video.

**Comment by MasayukiSuda** [comment]
Not support

**Comment by stonyz** [comment]
Thanks. btw, if you set another filter when record, the app will crash some time.  (run the sample )

```

java.lang.IllegalStateException: Could not get attrib or uniform location for aPosition
    at com.daasuu.camerarecorder.egl.filter.GlFilter.getHandle(GlFilter.java:177)
    at com.daasuu.camerarecorder.egl.filter.GlFilter.draw(GlFilter.java:136)
    at com.daasuu.camerarecorder.capture.EncodeRenderHandler.run(EncodeRenderHandler.java:225)
    at java.lang.Thread.run(Thread.java:764)
```
